name: Generate Shorts
on:
  schedule:
    - cron: '0 */6 * * *' # Runs every 6 hours
  workflow_dispatch:      # Manual run button

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg imagemagick
          # Fix ImageMagick security policy to allow TextClip
          sudo sed -i 's/policy domain="path" rights="none" pattern="@\*"/policy domain="path" rights="read|write" pattern="@*"/g' /etc/ImageMagick-6/policy.xml

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python Libraries
        run: pip install -r requirements.txt

      - name: Run Script
        run: python main.py

      - name: Save Video to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: youtube-short-${{ github.run_id }}
          path: output_short.mp4
